package model.enumi;

public enum ButtonEnabled {
	
	ADD_PRODUCT_DISABLE, REMOVE_PRODUCT_ENABLE, REMOVE_PRODUCT_DISABLE, 
	FINISH_ENABLE, FINISH_DISABLE, BUY_ENABLE, BUY_DISABLE, DELETE_ORDER_DISABLE;
	
}
